---
openapi: 3.0.1
info:
  title: Seismic API
  version: v1
  description: API to retrieve seismic data from USGS and create comments on features
basePath: "/"
servers:
- url: http://localhost:3000
  description: Local Environment
paths:
  "/api/features/{feature_id}/comments":
    post:
      summary: Creates a comment for a feature
      tags:
      - Comments
      parameters:
      - name: feature_id
        in: path
        required: true
        description: ID of feature to comment on
        schema:
          type: string
      responses:
        '201':
          description: comment created
        '404':
          description: feature not found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                body:
                  type: string
              required:
              - body
  "/api/features":
    get:
      summary: Retrieves all features
      tags:
      - Features
      parameters:
      - name: page
        in: query
        description: Page number
        schema:
          type: integer
      - name: per_page
        in: query
        description: Number of items per page
        schema:
          type: integer
      - name: mag_type
        in: query
        description: Filter by magnitude type
        schema:
          type: string
      responses:
        '200':
          description: features found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        external_id:
                          type: string
                        title:
                          type: string
                        magnitude:
                          type: number
                          format: float
                        place:
                          type: string
                        mag_type:
                          type: string
                        url:
                          type: string
                          format: uri
                          x-nullable: true
                        tsunami:
                          type: boolean
                        coordinates:
                          type: object
                          properties:
                            latitude:
                              type: number
                              format: float
                            longitude:
                              type: number
                              format: float
                        links:
                          type: object
                          properties:
                            external_url:
                              type: string
                              format: uri
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      total:
                        type: integer
                      per_page:
                        type: integer
                required:
                - data
                - pagination
